target-version = "py312"
line-length = 88

[lint]
select = ["E", "F", "I", "UP"]
ignore = []
fixable = ["ALL"]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[lint.isort]
known-first-party = ["djpyworkshop"]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]
combine-as-imports = true